### ISSUE TITLE
Donors added to convertkit before donation is actually complete

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-convertkit#6]
## Issue Overview
Since the addon is using `give_insert_payment` as the hook to work the magic on, if a donation isn't completed at Paypal, the user is still added to a convertkit list. This is problematic.

## Expected Behavior
We should only add a donor to a list after the donation is marked as complete. 

## Current Behavior
Donations are pending and then abandoned (as they should be) but the donor email is still added to convertkit.

## Possible Solution
Perhaps using the same hook that our donation confirmation/ admin notification emails are sent on would work.

## Steps to Reproduce (for bugs)
1. Set up convertkit addon and a form with paypal standard
2. Submit a donation, but don't complete it at PayPal
3. Donation is pending, but the donor email has already been added to Paypal. 

## Todos
- [ ] Tests

**Comment by DevinWalker** [comment]
If the donor opts-in at the time of donation they will be added to the list(s) regardless of whether the donation status was completed successfully or not. There is no connection between a successful donation and the donor's email being added to a mailing list. As long as they opted-in, they will be added to the list.
